"""empty message

Revision ID: 6c381e32c4ff
Revises: a51234924fb3
Create Date: 2022-08-30 17:54:20.188402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c381e32c4ff'
down_revision = 'a51234924fb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
