"""empty message

Revision ID: 86601c8da174
Revises: 6c381e32c4ff
Create Date: 2022-09-01 18:05:44.561736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86601c8da174'
down_revision = '6c381e32c4ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_moderators_vk_id', table_name='moderators')
    op.create_index(op.f('ix_moderators_vk_id'), 'moderators', ['vk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moderators_vk_id'), table_name='moderators')
    op.create_index('ix_moderators_vk_id', 'moderators', ['vk_id'], unique=False)
    # ### end Alembic commands ###
