version: "3.9"
services:
  postgres:
    image: postgres:14.4-alpine
    container_name: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file: ../.env.dev
    ports:
      - 5432:5432

volumes:
  pg-data:
