version: "3.9"
services:
  postgres:
    image: postgres:14.4-alpine
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: ./.env.dev
    ports:
      - 5432:5432

  redis:
    image: redis:7.0.4-alpine
    container_name: redis
    env_file: ./.env.dev
    ports:
      - 6379:6379
