version: "3.9"
services:
  postgres:
    image: postgres:14.4-alpine
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: ./.env.prod
    ports:
      - 5432:5432
    networks:
      - magic_helper_network

  redis:
    image: redis:7.0.4-alpine
    container_name: redis
    volumes:
      - redis-data:/var/lib/redis/data
    env_file: ./.env.prod
    depends_on:
      - postgres
    networks:
      - magic_helper_network

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: api
    env_file: ./.env.prod
    depends_on:
      - redis
    networks:
      - magic_helper_network

  nginx_backend:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx_backend
    depends_on:
      - api
    ports:
      - 443:443
    networks:
      - magic_helper_network

networks:
  magic_helper_network:
    driver: bridge
    name: magic_helper_network

volumes:
  postgres-data:
  redis-data:


